version: "3.7"

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    networks:
      AIservice:
        aliases:
          - frontend.docker
    depends_on:
      - backend
    volumes:
        - ./frontend:/app
        - ./storage:/storage

  backend:
    build: smartbard
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
          - backend.docker
    volumes:
      - ./smartbard:/app
      - ./storage:/storage
